### ISSUE TITLE
Home.css && login.css

### ISSUE THREAD

**Issue by olanhealy** [olanhealy/CS4116_Group_Project#21]
I believe these files should be stored in the css directory. It is possible to make the file location point places in project so I think both should be moved into css
![image](https://github.com/olanhealy/CS4116_Group_Project/assets/100354771/65d0abf3-2cb6-4542-90de-53f0ebd40c08)

**Comment by olanhealy** [comment]
@AdamTCollins @CaoimheCahill Can this be closed?

**Comment by CaoimheCahill** [comment]
Issue Resolved
